### PR TITLE
Fixes incorrect assertion check from #17

### PR DESCRIPTION
**Pull request by IshaanDesai**
## Description

Fixes https://github.com/precice/dumux-adapter/issues/17.

## Checklist

- [x] I made sure that the source files are formatted properly.

### CODE REVIEW

**Review by ajaust — APPROVED** [review]
Looks good. Did we not have any tests failing due to this mistake?

**Comment by IshaanDesai** [comment]
> Did we not have any tests failing due to this mistake?

Tests did not compile on my machine, but surprisingly the CI did not complain! Should I look into this or do you think this is expected?

**Comment by ajaust** [comment]
I think the problem is the line
```text
dunecontrol --only=dumux-precice --opts=./dumux-precice/test/cmake-test.opts all
```
in our CI (both testing CIs). The repository has been renamed to `dumux-adapter` so this path (and maybe some others in the CI configuration) could be out of date. That the assertion did not create an error in the CI during compilation could be a hint that the test was compiled with `DNDEBUG` flags. I see this could be the default setting for CMake/DUNE if not (valid?) options file is specified.

**Comment by ajaust** [comment]
But regarding your question. I think it is fine to merge to fix this issue and maybe investigate the broken CI afterwards. I would expect the CI to fail for issues like this wrong assertion.

**Pull request merged**
