### PR TITLE
Restructure the user documentation

### LINKED ISSUE #35: Duplicate user documentation files
I am currently reviewing https://github.com/precice/precice.github.io/pull/364, which copies over the `README.md` file into the website. This is a duplication we should try to avoid, therefore I am in the process of rendering the documentation directly from the repository.

Looking into the repository, I noticed the following duplicate resources:

## README.md

Last changed recently.

Includes:

- Structure of the repository
- Installation
- Documentation
- Publications

## doc/user

Some files changed recently, some less months/years ago.

Includes:

- `index.md`:
  - Something like the basic information that `README.md` should have. 
  - Duplication: The sections "API documentation", "How to cite this code", "Publications" are almost identical to the `README.md`.
- `overview.md`:
  - Structure of the repository
  - Duplication: The structure of the repository is almost identical to the section in the `README.md`.
- `installation.md`:
  - Duplication: The installation section from the README is almost identical. Both documents seem to contain some information that the other does not. The `README.md` looks more recent. Main part of information that is missing from the `README.md` is this paragraph (@IshaanDesai @mathiskelm @Fujikawas is this still important?):
   > To use the adapter in a separate DUNE module, we recommend building the adapter as a shared library. To do so, use the CMake option `-DBUILD_SHARED_LIBS=ON` to build the adapter and upstream modules. The DuMux install script uses `dumux/cmake.opts`, which already sets this option.
   > Note that to change this setting it may be required to clear the CMake caches in `build-cmake/CMakeCache.txt`.
- `example-usage.md`:
  - Some notes on using the adapter in DUNE solver codes, and a reference to `examples/`
  - No duplication, but I guess still useful.
- `example-cases.md`: 
  - describing some tutorials
  - No duplication with the README.md or with the tutorials. But these cases seem to be under development, so I would not render this page on the website.

## Suggestion

In a pull request, I will do the following:

- [x] Move any information in the `README.md` but not in `doc/user/docs` in the individual files there, synchronizing them.
   - [x] Move installation instructions
   - [x] Move publications/citing 
- [x] Reduce the `README.md` to the very basic information.
- [x] Remove the `index.md` and potentially move some information into the `overview.md`
- [x] **Remove anything related to MkDocs** (I understand you do not use this, right? Potentially @ajaust knows more?)
- [x] Render the files `overview.md`, `installation.md` (renamed to `get.md`), `example-usage.md` (renamed to `use.md`) on the website. Not render `example-cases.md`, but keep it here.

Do you agree/protest? Any other suggestions?

### PR DESCRIPTION
**Pull request by MakisH**
## Description

See the commit history and the steps described in https://github.com/precice/dumux-adapter/issues/35 (closes #35).

I have not removed any information (beisdes the mkdoc files), I have only moved things around. The documentation is not yet rendered on the website.

**Edit:** I also replaced the previous way this repo was linting markdown files, with the same pre-commit now used everywhere else. I also ported the (very useful) step to format preCICE config files, thus some changes there.

@IshaanDesai: Please do a quick sanity check and maybe view the repository at this state to see if everything looks as you would expect it. Let's not update any content here.

## Checklist

- [x] I made sure that the source files are formatted properly.
- [ ] I added my changes to the changelog (`CHANGELOG.md`)
- [x] I updated the documentation.

### CODE REVIEW

**Comment by MakisH** [comment]
I will actually go one step further and move the documentation directly to `docs/` and rename the `doc/`.

**Comment by MakisH** [comment]
Sorry for the messy commits, I was trying to make all linters happy. Now it's really ready to review.

**Review by IshaanDesai — APPROVED** [review]
I went through all the changes and also checked the files in the rendered form on GitHub. Looks good, thanks a lot of this :pray:

**Comment by MakisH** [comment]
Perfect timing! Thanks! :hugs:

**Pull request merged**
